spring.application.name=EDLB
server.port=9090
#Configuration base de donnée Mongo

spring.data.mongodb.host=${MONGO_DB_HOST}
spring.data.mongodb.port=${MONGODB_PORT}
spring.data.mongodb.database=${MONGODB_DATABASE}
spring.data.mongodb.password=${MONGODB_PSSWRD}
spring.data.mongodb.username=${MONGODB_USR}
spring.data.mongodb.authentication-database=${MONGODB_AUTH}
#Configuration base de donnée JPA

security.jwt.secret-key=${JWT_KEY}

# Expiration du token en millisecondes
security.jwt.expiration-time=${JWT_TIME}

# Database config
spring.datasource.url=${SPRING_SOURCE}
spring.datasource.username=${SPRING_USR}
spring.datasource.password=${SPRING_PSSWRD}
spring.datasource.driver-class-name=${SPRING_DRIVER}
spring.datasource.platform=${SPRING_PLATFORM}
spring.jpa.database-platform=${SPRING_DB_PLATFORM}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

# Optionnel : Configure les logs de la SQL pour débogage
spring.jpa.show-sql=${SPRING_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${SPRING_FORMAT_SQL}
spring.output.ansi.enabled=${SPRING_OUTPUT}


# Configurations OAuth2 Resource Server avec JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH}

